import type { Metadata } from 'next';
import Breadcrumb from '@/components/ui/Breadcrumb';

export const metadata: Metadata = {
    title: "Terms of Service | NormalMapGenerator.io",
    description: "Terms of Service for using NormalMapGenerator.io free online normal map tool.",
    alternates: { canonical: '/terms' },
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-zinc-950 pt-24 pb-12">
            <div className="max-w-4xl mx-auto px-4">
                <Breadcrumb items={[{ label: 'Terms of Service' }]} />

                <div className="text-zinc-300">
                    <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>

                    <div className="space-y-8 bg-zinc-900/50 p-8 rounded-2xl border border-zinc-800/50">
                        <section>
                            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                            <p>
                                By accessing and using NormalMapGenerator.io ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-white mb-3">2. Use License</h2>
                            <p>
                                NormalMapGenerator.io is a free tool provided for both personal and commercial use. You are free to use the maps generated by this tool in your projects without attribution (though attribution is appreciated).
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-white mb-3">3. Disclaimer</h2>
                            <p>
                                The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, expressed or implied, regarding the reliability, accuracy, or availability of the Service. We are not responsible for any data loss (though unlikely as processing is local) or damages resulting from the use of this tool.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-white mb-3">4. Intellectual Property</h2>
                            <p>
                                The images you process using our tool remain your property. Since processing happens locally in your browser, we claim no rights or ownership over your content.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-white mb-3">5. Contact</h2>
                            <p>
                                For any inquiries regarding these Terms, please contact us at: <a href="mailto:contact@normalmapgenerator.io" className="text-cyan-400 hover:text-cyan-300 font-medium">contact@normalmapgenerator.io</a>
                            </p>
                        </section>

                        <p className="text-sm text-zinc-500 pt-4 border-t border-zinc-800">Last updated: {new Date().toLocaleDateString()}</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
